### ISSUE TITLE
no components.m

### ISSUE THREAD

**Issue by Myzhencai** [hexygen/structure-aware-correspondence#1]
@hexygen  hello ,thanks for sharing here is the test of the code : 
![2018-07-31 18-07-38](https://user-images.githubusercontent.com/21084423/43453489-d353e7ee-94ec-11e8-8dac-3d0788d415cd.png)
it seems there is no components.m , I just want to get the correspondence point of two mesh to get them do the deformation transfer , thanks for sharing some time for the issue ,have a nice day . ;-)

**Comment by hexygen** [comment]
This is part of MatlabBGL, see the "Prerequisites" in the readme file.

**Comment by Myzhencai** [comment]
@hexygen have solved the issue , thanks ;-).
