### ISSUE TITLE
Internal MATLAB error using run_breaksymmetry.m

### ISSUE THREAD

**Issue by PietroMsn** [hexygen/structure-aware-correspondence#3]
Hello, 
I'm having a problem in using this code for point clouds. I run run_example.m with point cloud setting for one of the shapes (a triangular mesh for the other one)  and everything works fine. Then when I'm trying to use run_breaksymmetry.m using as input the segmentation obtained It crashes with an internal MATLAB error (in the attached file reportBreakSymmetry.txt). In mesh vs mesh setting everything is fine, maybe you can have some suggestions on the reasons why it happens.
Thank you very much.
[reportBreakSymmetry.txt](https://github.com/hexygen/structure-aware-correspondence/files/3043870/reportBreakSymmetry.txt)

**Comment by hexygen** [comment]
Hi Pietro,
It seems that the included geodesic computation package is not compiled correctly for your machine. You can try to recompile it using geodesics_matlab/mex_compile. This is an external package from https://code.google.com/archive/p/geodesic/ so if that doesn't work try to follow the instructions there.
